# Generated by Django 2.1.4 on 2018-12-17 13:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=254)),
                ('branch_location', models.CharField(default='', max_length=254)),
                ('branch_address', models.CharField(default='', max_length=254)),
            ],
            options={
                'db_table': 'branch',
                'ordering': ('branch_name',),
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=254)),
                ('address', models.CharField(default='', max_length=509)),
                ('contact_person', models.CharField(default='', max_length=254)),
                ('contact_no', models.CharField(default='', max_length=254, validators=[django.core.validators.RegexValidator('^((\\+92)|(0092))-{0,1}\\d{3}-{0,1}\\d{7}$|^\\d{11}$|^\\d{4}-\\d{7}$')])),
                ('logo', models.ImageField(upload_to='company_logo')),
            ],
            options={
                'db_table': 'company',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_start_date', models.DateField()),
                ('subscription_end_date', models.DateField()),
                ('charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, validators=[django.core.validators.RegexValidator('^(\\d+)(\\.00)')])),
                ('centangle_percentage', models.IntegerField(validators=[django.core.validators.RegexValidator('d{2}')])),
            ],
            options={
                'db_table': 'license',
                'ordering': ('charges',),
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nol', models.IntegerField(blank=True, default=0, null=True)),
                ('cylc', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, validators=[django.core.validators.RegexValidator('^(\\d+)(\\.00)')])),
                ('paid_cylc', models.BooleanField(default=False)),
                ('tottic', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, validators=[django.core.validators.RegexValidator('^(\\d+)(\\.00)')])),
                ('paid_tottic', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'report',
                'ordering': ('nol',),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branchID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='License.Branch')),
                ('name', models.CharField(default=False, max_length=254)),
                ('charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, validators=[django.core.validators.RegexValidator('^(\\d+)(\\.00)')])),
            ],
            options={
                'db_table': 'service',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='report',
            name='branchID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='License.Branch'),
        ),
        migrations.AddField(
            model_name='branch',
            name='companyID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='License.Company'),
        ),
        migrations.AddField(
            model_name='branch',
            name='licenseID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='License.License'),
        ),
    ]
